-- 0002_seed_tohop.sql
-- Seed standard Vietnamese university admission tổ hợp codes
-- Reference: Ministry of Education standard combinations

INSERT INTO tohop_codes (code, subjects, label_vi) VALUES
  ('A00', ARRAY['Toan','Ly','HoaHoc'], 'Toán - Lý - Hóa'),
  ('A01', ARRAY['Toan','Ly','Ngoai_ngu'], 'Toán - Lý - Tiếng Anh'),
  ('A02', ARRAY['Toan','Ly','Sinh'], 'Toán - Lý - Sinh'),
  ('A03', ARRAY['Toan','Ly','Ngu_van'], 'Toán - Lý - Ngữ văn'),
  ('A04', ARRAY['Toan','Ly','Dia_ly'], 'Toán - Lý - Địa lý'),
  ('A05', ARRAY['Toan','HoaHoc','Lich_su'], 'Toán - Hóa - Lịch sử'),
  ('A06', ARRAY['Toan','HoaHoc','Dia_ly'], 'Toán - Hóa - Địa lý'),
  ('A07', ARRAY['Toan','Lich_su','Dia_ly'], 'Toán - Lịch sử - Địa lý'),
  ('A08', ARRAY['Toan','Lich_su','GDCD'], 'Toán - Lịch sử - GDCD'),
  ('A09', ARRAY['Toan','Dia_ly','GDCD'], 'Toán - Địa lý - GDCD'),
  ('A10', ARRAY['Toan','Ly','GDCD'], 'Toán - Lý - GDCD'),
  ('A11', ARRAY['Toan','HoaHoc','Ngu_van'], 'Toán - Hóa - Ngữ văn'),
  ('A14', ARRAY['Toan','HoaHoc','Ngoai_ngu'], 'Toán - Hóa - Tiếng Anh'),
  ('A16', ARRAY['Toan','Ngu_van','Ngoai_ngu'], 'Toán - Ngữ văn - Tiếng Anh'),
  ('B00', ARRAY['Toan','HoaHoc','Sinh'], 'Toán - Hóa - Sinh'),
  ('B01', ARRAY['Toan','Sinh','Lich_su'], 'Toán - Sinh - Lịch sử'),
  ('B02', ARRAY['Toan','Sinh','Dia_ly'], 'Toán - Sinh - Địa lý'),
  ('B03', ARRAY['Toan','Sinh','Ngu_van'], 'Toán - Sinh - Ngữ văn'),
  ('B04', ARRAY['Toan','Sinh','GDCD'], 'Toán - Sinh - GDCD'),
  ('B08', ARRAY['Toan','Sinh','Ngoai_ngu'], 'Toán - Sinh - Tiếng Anh'),
  ('C00', ARRAY['Ngu_van','Lich_su','Dia_ly'], 'Ngữ văn - Lịch sử - Địa lý'),
  ('C01', ARRAY['Ngu_van','Toan','Ly'], 'Ngữ văn - Toán - Lý'),
  ('C02', ARRAY['Ngu_van','Toan','HoaHoc'], 'Ngữ văn - Toán - Hóa'),
  ('C03', ARRAY['Ngu_van','Toan','Lich_su'], 'Ngữ văn - Toán - Lịch sử'),
  ('C04', ARRAY['Ngu_van','Toan','Dia_ly'], 'Ngữ văn - Toán - Địa lý'),
  ('C05', ARRAY['Ngu_van','Ly','HoaHoc'], 'Ngữ văn - Lý - Hóa'),
  ('C14', ARRAY['Ngu_van','Toan','GDCD'], 'Ngữ văn - Toán - GDCD'),
  ('C19', ARRAY['Ngu_van','Lich_su','GDCD'], 'Ngữ văn - Lịch sử - GDCD'),
  ('C20', ARRAY['Ngu_van','Dia_ly','GDCD'], 'Ngữ văn - Địa lý - GDCD'),
  ('D01', ARRAY['Ngu_van','Toan','Ngoai_ngu'], 'Ngữ văn - Toán - Tiếng Anh'),
  ('D03', ARRAY['Ngu_van','Toan','Ngoai_ngu'], 'Ngữ văn - Toán - Tiếng Pháp'),
  ('D06', ARRAY['Ngu_van','Toan','Ngoai_ngu'], 'Ngữ văn - Toán - Tiếng Nhật'),
  ('D07', ARRAY['Toan','HoaHoc','Ngoai_ngu'], 'Toán - Hóa - Tiếng Anh'),
  ('D08', ARRAY['Toan','Sinh','Ngoai_ngu'], 'Toán - Sinh - Tiếng Anh'),
  ('D09', ARRAY['Toan','Lich_su','Ngoai_ngu'], 'Toán - Lịch sử - Tiếng Anh'),
  ('D10', ARRAY['Toan','Dia_ly','Ngoai_ngu'], 'Toán - Địa lý - Tiếng Anh'),
  ('D14', ARRAY['Ngu_van','Lich_su','Ngoai_ngu'], 'Ngữ văn - Lịch sử - Tiếng Anh'),
  ('D15', ARRAY['Ngu_van','Dia_ly','Ngoai_ngu'], 'Ngữ văn - Địa lý - Tiếng Anh')
ON CONFLICT (code) DO NOTHING;
